version: '2'

networks:
  elk:
    driver: bridge

services:

# elasticsearch
  elasticsearch:
    build:
      context: elk/elasticsearch/
    container_name: "elasticsearch"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./data:/data
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

# kibana
  kibana:
    build:
      context: elk/kibana/
    container_name: "kibana"
    ports:
      - "5601:5601"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

# logstash
  logstash:
    build: 
      context: elk/logstash/
    volumes:
      - ./data:/data
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

# dionaea
  dionaea:
    build:
      context: dionaea/
    container_name: "dionaea"
    stdin_open: true
    ports:
      - "20:20"
      - "21:21"
      - "42:42"
      - "69:69/udp"
      - "8081:80"
      - "135:135"
      - "443:443"
      - "445:445"
      - "1433:1433"
      - "1723:1723"
      - "1883:1883"
      - "3306:3306"
      - "5060:5060"
      - "5060:5060/udp"
      - "5061:5061"
      - "27017:27017"
    volumes:
      - ./data/dionaea/roots/ftp:/opt/dionaea/var/dionaea/roots/ftp
      - ./data/dionaea/roots/tftp:/opt/dionaea/var/dionaea/roots/tftp
      - ./data/dionaea/roots/www:/opt/dionaea/var/dionaea/roots/www
      - ./data/dionaea/roots/upnp:/opt/dionaea/var/dionaea/roots/upnp
      - ./data/dionaea:/opt/dionaea/var/dionaea
      - ./data/dionaea/binaries:/opt/dionaea/var/dionaea/binaries
      - ./data/dionaea/log:/opt/dionaea/var/log
      - ./data/dionaea/rtp:/opt/dionaea/var/dionaea/rtp
      - ./data/dionaea/bitstreams:/opt/dionaea/var/dionaea/bistreams
